### ISSUE TITLE
Replace `boost::` with `std::` counterpart

### ISSUE THREAD

**Issue by lwygzh** [loco-3d/crocoddyl#1251]
**Is your feature request related to a problem? Please describe.**
I noticed that `crocoddyl` mainly relies on Boost to create shared pointers and other pointer related functionalities. This has been already supported by the C++ standard library. The reliance on boost makes it harder to compile from source, especially on MacOS, where it leads to many compilation errors.

**Describe the solution you'd like**
Replace `boost::shared_ptr`, `boost::allocate_shared`, `boost::static_pointer_cast`, `boost::dynamic_pointer_cast` with their `std::` counterparts.

**Describe alternatives you've considered**
No other alternatives.

**Additional context**
No additional context.

**Comment by cmastalli** [comment]
Python bindings of Crocoddyl depend on boost-python, and this won't change due to constraints with its dependencies (Pinocchio and eigenpy). Moreover, Boost-python doesn't bind properly `std::shared_ptr`. This makes the proposed solution inconvenient.

I work with MacOS and the installation of Boost is as simple as in Linux.
