### ISSUE TITLE
Moving to a more recent C++ standard

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#934]
With 16.04 reaching EOL next month and C++11 about ten years old, I wonder if there are requirements to continue to support C++98 in the community? In practice we _implicitly_ already require C++11 support (e.g. for URDF parsing in Pinocchio which translates to Crocoddyl) [1] and officially moving the minimum supported standard to a newer version could simplify development by benefitting from new features (e.g. using `chrono` in #931). I'd love to hear thoughts and plans on this topic for future developments :-).

[1] Our buildserver on Xenial also appears to require `CMAKE_CXX_STANDARD=11` for more than a year now (https://github.com/loco-3d/crocoddyl/commit/34bdda2e4d79c3295a1cba7dbc46d3d62bc4f9fa). I can't see the gepgitlab config so Guilhem would have to comment on that.

**Comment by cmastalli** [comment]
I am in with moving to c++11

**Comment by nim65s** [comment]
I think we could even move directly to C++14. 

I've seen many cases where developers think they are using a C++11 feature, while it is in fact a C++14 feature (eg. using `auto` as a function return type), and it works on their computer because the default standard is >= 14, but raises boring issues when they want to share their work.

I think the oldest system we support is 16.04, and activating C++11 or C++14 on 16.04 is the same thing.


To answer about the implicit requirement, I don't think this is the case. On gitlab, pinocchio is using urdfdom v0.4 provided by ubuntu, which doesn't require C++11.

**Comment by proyan** [comment]
I've already stated my preference for updating our base support to c++11. If we can move to c++14, that is even better from my perspective. Crocoddyl is supposed to be on the working on the robot, and I don't think any current robots still operate on 12.04.
And Ubuntu 14.04 has c++14 support.  (https://www.gnu.org/software/gcc/projects/cxx-status.html#cxx14)
So I am okay with moving directly to c++14.

**Comment by cmastalli** [comment]
I think we can close this issue (see #949 for more details)
